image: registry.gitlab.fpcomplete.com/fpco/default-build-image:2937

lint:
  script:
    -  scripts/ci/tfinit.sh
    -  scripts/ci/tflint.sh
#   -  scripts/ci/undeclared-variables.sh

test:
  script:
    - scripts/ci/examples/tfbuild.sh
    - scripts/ci/examples/tftest.sh
    - scripts/ci/examples/tfclean.sh
